### ISSUE TITLE
input data

### ISSUE THREAD

**Issue by BioEpi** [ysora/stripenn#5]
Hello,
    Thanks for developing this great tool analyzing Stripe. I have 1 question:
    the input contact matrix is must be not normalized/balancing contact matrix, right? can I provided iced normalized contact matrix to Stripenn?
Best,

**Comment by ysora** [comment]
You can input both raw/normalized/balancing data.
Let me know if you have any issues.
FYI, if you have some error running stripenn, please set -n 1 parameter since there is an issue with parallel package.
Thanks

Best,
Sora

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: bxhu ***@***.***>
Sent: Saturday, September 24, 2022 5:34:17 PM
To: ysora/stripenn ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [ysora/stripenn] input data (Issue #5)


Hello,
Thanks for developing this great tool analyzing Stripe. I have 1 question:
the input contact matrix is must be not normalized/balancing contact matrix, right? can I provided iced normalized contact matrix to Stripenn?
Best,

**Comment by BioEpi** [comment]
thanks a lot.
what is the minimum valid pairs? Are 200million valid pairs enough to call Stripes?

**Comment by ysora** [comment]
Yes, 200M is enough!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: bxhu ***@***.***>
Sent: Saturday, September 24, 2022 6:19:49 PM
To: ysora/stripenn ***@***.***>
Cc: Yoon, Sora ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [ysora/stripenn] input data (Issue #5)


thanks a lot.
what is the minimum valid pairs? Are 200million valid pairs enough to call Stripes?

**Comment by ysora** [comment]
Minimum is 100~150M I think

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: bxhu ***@***.***>
Sent: Saturday, September 24, 2022 6:19:49 PM
To: ysora/stripenn ***@***.***>
Cc: Yoon, Sora ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [ysora/stripenn] input data (Issue #5)


thanks a lot.
what is the minimum valid pairs? Are 200million valid pairs enough to call Stripes?

**Comment by BioEpi** [comment]
thanks a lot.
